# Generated by Django 3.2 on 2023-04-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=256, verbose_name='aAellidos')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('tipo', models.CharField(max_length=128, verbose_name='Tipo')),
                ('horario_particip', models.CharField(max_length=128, verbose_name='Horario_particip')),
                ('img', models.CharField(max_length=128, verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
    ]
