# Generated by Django 3.2 on 2023-04-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
